# frozen_string_literal: true

module PAWS
  module GameData
    # Snapshot metadata used by the extractor to decode condact opcodes and arity.
    # Execution dispatch lives in CondactRegistry and the condact handlers.
    module CondactMetadata
      DEFINITIONS = {
        0 => { name: "AT", params: 1 },
        1 => { name: "NOTAT", params: 1 },
        2 => { name: "ATGT", params: 1 },
        3 => { name: "ATLT", params: 1 },
        4 => { name: "PRESENT", params: 1 },
        5 => { name: "ABSENT", params: 1 },
        6 => { name: "WORN", params: 1 },
        7 => { name: "NOTWORN", params: 1 },
        8 => { name: "CARRIED", params: 1 },
        9 => { name: "NOTCARR", params: 1 },
        10 => { name: "CHANCE", params: 1 },
        11 => { name: "ZERO", params: 1 },
        12 => { name: "NOTZERO", params: 1 },
        13 => { name: "EQ", params: 2 },
        14 => { name: "GT", params: 2 },
        15 => { name: "LT", params: 2 },
        16 => { name: "ADJECT1", params: 1 },
        17 => { name: "ADVERB", params: 1 },
        18 => { name: "INVEN", params: 0 },
        19 => { name: "DESC", params: 0 },
        20 => { name: "QUIT", params: 0 },
        21 => { name: "END", params: 0 },
        22 => { name: "DONE", params: 0 },
        23 => { name: "OK", params: 0 },
        24 => { name: "ANYKEY", params: 0 },
        25 => { name: "SAVE", params: 0 },
        26 => { name: "LOAD", params: 0 },
        27 => { name: "TURNS", params: 0 },
        28 => { name: "SCORE", params: 0 },
        29 => { name: "CLS", params: 0 },
        30 => { name: "DROPALL", params: 0 },
        31 => { name: "AUTOG", params: 0 },
        32 => { name: "AUTOD", params: 0 },
        33 => { name: "AUTOW", params: 0 },
        34 => { name: "AUTOR", params: 0 },
        35 => { name: "PAUSE", params: 1 },
        36 => { name: "TIMEOUT", params: 0 },
        37 => { name: "GOTO", params: 1 },
        38 => { name: "MESSAGE", params: 1 },
        39 => { name: "REMOVE", params: 1 },
        40 => { name: "GET", params: 1 },
        41 => { name: "DROP", params: 1 },
        42 => { name: "WEAR", params: 1 },
        43 => { name: "DESTROY", params: 1 },
        44 => { name: "CREATE", params: 1 },
        45 => { name: "SWAP", params: 2 },
        46 => { name: "PLACE", params: 2 },
        47 => { name: "SET", params: 1 },
        48 => { name: "CLEAR", params: 1 },
        49 => { name: "PLUS", params: 2 },
        50 => { name: "MINUS", params: 2 },
        51 => { name: "LET", params: 2 },
        52 => { name: "NEWLINE", params: 0 },
        53 => { name: "PRINT", params: 1 },
        54 => { name: "SYSMESS", params: 1 },
        55 => { name: "ISAT", params: 2 },
        56 => { name: "COPYOF", params: 2 },
        57 => { name: "COPYOO", params: 2 },
        58 => { name: "COPYFO", params: 2 },
        59 => { name: "COPYFF", params: 2 },
        60 => { name: "LISTOBJ", params: 0 },
        61 => { name: "EXTERN", params: 1 },
        62 => { name: "RAMSAVE", params: 0 },
        63 => { name: "RAMLOAD", params: 1 },
        64 => { name: "BEEP", params: 2 },
        65 => { name: "PAPER", params: 1 },
        66 => { name: "INK", params: 1 },
        67 => { name: "BORDER", params: 1 },
        68 => { name: "PREP", params: 1 },
        69 => { name: "NOUN2", params: 1 },
        70 => { name: "ADJECT2", params: 1 },
        71 => { name: "ADD", params: 2 },
        72 => { name: "SUB", params: 2 },
        73 => { name: "PARSE", params: 0 },
        74 => { name: "LISTAT", params: 1 },
        75 => { name: "PROCESS", params: 1 },
        76 => { name: "SAME", params: 2 },
        77 => { name: "MES", params: 1 },
        78 => { name: "CHARSET", params: 1 },
        79 => { name: "NOTEQ", params: 2 },
        80 => { name: "NOTSAME", params: 2 },
        81 => { name: "MODE", params: 2 },
        82 => { name: "LINE", params: 1 },
        83 => { name: "TIME", params: 2 },
        84 => { name: "PICTURE", params: 1 },
        85 => { name: "DOALL", params: 1 },
        86 => { name: "PROMPT", params: 1 },
        87 => { name: "GRAPHIC", params: 1 },
        88 => { name: "ISNOTAT", params: 2 },
        89 => { name: "WEIGH", params: 2 },
        90 => { name: "PUTIN", params: 2 },
        91 => { name: "TAKEOUT", params: 2 },
        92 => { name: "NEWTEXT", params: 0 },
        93 => { name: "ABILITY", params: 2 },
        94 => { name: "WEIGHT", params: 1 },
        95 => { name: "RANDOM", params: 1 },
        96 => { name: "INPUT", params: 1 },
        97 => { name: "SAVEAT", params: 0 },
        98 => { name: "BACKAT", params: 0 },
        99 => { name: "PRINTAT", params: 2 },
        100 => { name: "WHATO", params: 0 },
        101 => { name: "RESET", params: 1 },
        102 => { name: "PUTO", params: 1 },
        103 => { name: "NOTDONE", params: 0 },
        104 => { name: "AUTOP", params: 1 },
        105 => { name: "AUTOT", params: 1 },
        106 => { name: "MOVE", params: 1 },
        107 => { name: "PROTECT", params: 0 },
      }.freeze

      module_function

      def fetch(opcode)
        DEFINITIONS[opcode]
      end
    end
  end
end
